name: Deploy Astro site to GitHub Pages

on:
  push:
    branches:
      - prod  # Trigger only when there's a push to prod (e.g., after PR merge)

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment with a stable version
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20  # Changed to a stable version

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 3: Install npm dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Build the Astro site
      - name: Build Astro site
        run: npm run build

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Astro outputs the static site to the `dist/` directory
          publish_branch: gh-pages  # Changed to the default GitHub Pages branch
